<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Recipe extends \App\Entity\Recipe implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'calories' => [parent::class, 'calories', null],
        "\0".parent::class."\0".'carbs' => [parent::class, 'carbs', null],
        "\0".parent::class."\0".'categories' => [parent::class, 'categories', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'fat' => [parent::class, 'fat', null],
        "\0".parent::class."\0".'forHowManyPeople' => [parent::class, 'forHowManyPeople', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'imageUrl' => [parent::class, 'imageUrl', null],
        "\0".parent::class."\0".'ingredient' => [parent::class, 'ingredient', null],
        "\0".parent::class."\0".'protein' => [parent::class, 'protein', null],
        "\0".parent::class."\0".'step' => [parent::class, 'step', null],
        "\0".parent::class."\0".'title' => [parent::class, 'title', null],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null],
        "\0".parent::class."\0".'upVote' => [parent::class, 'upVote', null],
        "\0".parent::class."\0".'userID' => [parent::class, 'userID', null],
        'calories' => [parent::class, 'calories', null],
        'carbs' => [parent::class, 'carbs', null],
        'categories' => [parent::class, 'categories', null],
        'description' => [parent::class, 'description', null],
        'fat' => [parent::class, 'fat', null],
        'forHowManyPeople' => [parent::class, 'forHowManyPeople', null],
        'id' => [parent::class, 'id', null],
        'imageUrl' => [parent::class, 'imageUrl', null],
        'ingredient' => [parent::class, 'ingredient', null],
        'protein' => [parent::class, 'protein', null],
        'step' => [parent::class, 'step', null],
        'title' => [parent::class, 'title', null],
        'type' => [parent::class, 'type', null],
        'upVote' => [parent::class, 'upVote', null],
        'userID' => [parent::class, 'userID', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
