<?php

namespace ContainerD4t6KhO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\Api\\RecipeController::recent' => ['privates', '.service_locator.btwogvC.App\\Controller\\Api\\RecipeController::recent()', 'getRecipeControllerrecentService', true],
            'App\\Controller\\Api\\RecipeController::categories' => ['privates', '.service_locator.GVqZ9Id.App\\Controller\\Api\\RecipeController::categories()', 'getRecipeControllercategoriesService', true],
            'App\\Controller\\Api\\RecipeController::types' => ['privates', '.service_locator.J6mK8KI.App\\Controller\\Api\\RecipeController::types()', 'getRecipeControllertypesService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\Api\\RecipeController:recent' => ['privates', '.service_locator.btwogvC.App\\Controller\\Api\\RecipeController::recent()', 'getRecipeControllerrecentService', true],
            'App\\Controller\\Api\\RecipeController:categories' => ['privates', '.service_locator.GVqZ9Id.App\\Controller\\Api\\RecipeController::categories()', 'getRecipeControllercategoriesService', true],
            'App\\Controller\\Api\\RecipeController:types' => ['privates', '.service_locator.J6mK8KI.App\\Controller\\Api\\RecipeController::types()', 'getRecipeControllertypesService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\Api\\RecipeController::recent' => '?',
            'App\\Controller\\Api\\RecipeController::categories' => '?',
            'App\\Controller\\Api\\RecipeController::types' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\Api\\RecipeController:recent' => '?',
            'App\\Controller\\Api\\RecipeController:categories' => '?',
            'App\\Controller\\Api\\RecipeController:types' => '?',
        ]));
    }
}
