<?php

namespace ContainerD4t6KhO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecipeRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\RecipeRepository' shared autowired service.
     *
     * @return \App\Repository\RecipeRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\RecipeRepository'] = new \App\Repository\RecipeRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
