<?php

namespace ContainerD4t6KhO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecipeControllertypesService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.J6mK8KI.App\Controller\Api\RecipeController::types()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.J6mK8KI.App\\Controller\\Api\\RecipeController::types()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'typeRepository' => ['privates', 'App\\Repository\\TypeRepository', 'getTypeRepositoryService', true],
        ], [
            'typeRepository' => 'App\\Repository\\TypeRepository',
        ]))->withContext('App\\Controller\\Api\\RecipeController::types()', $container);
    }
}
