parameters:
  # Put parameters here that don't need to change on each machine where the app is deployed
  # https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\Controller\Api\RecipeController:
    class: App\Controller\Api\RecipeController
    autowire: true
    autoconfigure: true
    tags:
      - { name: controller.service_arguments }

  # makes classes in src/ available to be used as services
  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"
