<?php

namespace Container3U81LHU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurityManagerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Manager\SecurityManager' shared autowired service.
     *
     * @return \App\Manager\SecurityManager
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = new \Symfony\Component\PasswordHasher\Hasher\UserPasswordHasher(($container->privates['security.password_hasher_factory'] ?? $container->load('getSecurity_PasswordHasherFactoryService')));

        $container->services['App\\Manager\\SecurityManager'] = $instance = new \App\Manager\SecurityManager(($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), $a, ($container->services['lexik_jwt_authentication.jwt_manager'] ?? $container->load('getLexikJwtAuthentication_JwtManagerService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), $a);

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Manager\\SecurityManager', $container));

        return $instance;
    }
}
