<?php

namespace Container3U81LHU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUpVoteRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\UpVoteRepository' shared autowired service.
     *
     * @return \App\Repository\UpVoteRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\UpVoteRepository'] = new \App\Repository\UpVoteRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
