<?php

namespace Container3U81LHU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUpVoteControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Api\UpVoteController' shared autowired service.
     *
     * @return \App\Controller\Api\UpVoteController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Api\\UpVoteController'] = $instance = new \App\Controller\Api\UpVoteController(new \App\Manager\UpVoteManager(($container->privates['App\\Repository\\RecipeRepository'] ?? $container->load('getRecipeRepositoryService')), ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->privates['App\\Repository\\UpVoteRepository'] ?? $container->load('getUpVoteRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService'))));

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\Api\\UpVoteController', $container));

        return $instance;
    }
}
