<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWuRUcYo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWuRUcYo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWuRUcYo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWuRUcYo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWuRUcYo\App_KernelDevDebugContainer([
    'container.build_hash' => 'WuRUcYo',
    'container.build_id' => '69b069f4',
    'container.build_time' => 1727879135,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWuRUcYo');
