<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_api_all_recipes' => [[], ['_controller' => 'App\\Controller\\Api\\RecipeController::index'], [], [['text', '/api/recipes']], [], [], []],
    'app_api_recent_recipes' => [[], ['_controller' => 'App\\Controller\\Api\\RecipeController::recent'], [], [['text', '/api/recipe/recent']], [], [], []],
    'app_api_new_recipes' => [[], ['_controller' => 'App\\Controller\\Api\\RecipeController::new'], [], [['text', '/api/recipe/admin/new']], [], [], []],
    'app_api_update_recipes' => [[], ['_controller' => 'App\\Controller\\Api\\RecipeController::update'], [], [['text', '/api/recipe/admin/update']], [], [], []],
    'app_api_categories' => [[], ['_controller' => 'App\\Controller\\Api\\RecipeController::categories'], [], [['text', '/api/recipe/categories']], [], [], []],
    'app_api_types' => [[], ['_controller' => 'App\\Controller\\Api\\RecipeController::types'], [], [['text', '/api/recipe/types']], [], [], []],
    'app_api_specific_recipe' => [['title'], ['_controller' => 'App\\Controller\\Api\\RecipeController::specific'], [], [['variable', '/', '[^/]++', 'title', true], ['text', '/api/recipe']], [], [], []],
    'api_security_login' => [[], ['_controller' => 'App\\Controller\\Api\\SecurityController::login'], [], [['text', '/api/login']], [], [], []],
    'api_security_register' => [[], ['_controller' => 'App\\Controller\\Api\\SecurityController::register'], [], [['text', '/api/register']], [], [], []],
    'api_login_check' => [[], [], [], [['text', '/api/login_check']], [], [], []],
    'App\Controller\Api\RecipeController::index' => [[], ['_controller' => 'App\\Controller\\Api\\RecipeController::index'], [], [['text', '/api/recipes']], [], [], []],
    'App\Controller\Api\RecipeController::recent' => [[], ['_controller' => 'App\\Controller\\Api\\RecipeController::recent'], [], [['text', '/api/recipe/recent']], [], [], []],
    'App\Controller\Api\RecipeController::new' => [[], ['_controller' => 'App\\Controller\\Api\\RecipeController::new'], [], [['text', '/api/recipe/admin/new']], [], [], []],
    'App\Controller\Api\RecipeController::update' => [[], ['_controller' => 'App\\Controller\\Api\\RecipeController::update'], [], [['text', '/api/recipe/admin/update']], [], [], []],
    'App\Controller\Api\RecipeController::categories' => [[], ['_controller' => 'App\\Controller\\Api\\RecipeController::categories'], [], [['text', '/api/recipe/categories']], [], [], []],
    'App\Controller\Api\RecipeController::types' => [[], ['_controller' => 'App\\Controller\\Api\\RecipeController::types'], [], [['text', '/api/recipe/types']], [], [], []],
    'App\Controller\Api\RecipeController::specific' => [['title'], ['_controller' => 'App\\Controller\\Api\\RecipeController::specific'], [], [['variable', '/', '[^/]++', 'title', true], ['text', '/api/recipe']], [], [], []],
    'App\Controller\Api\SecurityController::login' => [[], ['_controller' => 'App\\Controller\\Api\\SecurityController::login'], [], [['text', '/api/login']], [], [], []],
    'App\Controller\Api\SecurityController::register' => [[], ['_controller' => 'App\\Controller\\Api\\SecurityController::register'], [], [['text', '/api/register']], [], [], []],
];
