<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3U81LHU\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3U81LHU/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container3U81LHU.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container3U81LHU\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container3U81LHU\App_KernelProdContainer([
    'container.build_hash' => '3U81LHU',
    'container.build_id' => '08fc49b9',
    'container.build_time' => 1727359556,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container3U81LHU');
